q_learning:
  learning_rate: 0.1
  discount_factor: 0.95
  initial_epsilon: 0.3
  epsilon_decay: 0.995
  min_epsilon: 0.01
  
state_encoder:
  score_buckets: 3
  
reward:
  profit_weight: 0.6
  conversion_weight: 0.4
  
training:
  epochs: 10
  batch_size: 100
  save_every: 5
  model_path: "data/q_table.pkl"